version: 2
preset:
  image: 'gantry-admin://images/layouts/offline.png'
  name: _offline
  timestamp: 1622634196
layout:
  /header/:
    -
      - 'logo-4653 30'
      - 'spacer-1191 70'
  /main/:
    -
      - system-messages-7396
    -
      - system-content-8538
  /footer/:
    -
      - position-footer
    -
      - 'copyright-4978 40'
      - 'spacer-5328 30'
      - 'branding-3333 30'
structure:
  header:
    attributes:
      boxed: ''
  main:
    attributes:
      boxed: ''
  footer:
    attributes:
      boxed: ''
content:
  position-footer:
    attributes:
      key: footer
