version: 2
preset:
  image: 'gantry-admin://images/layouts/home.png'
  name: home
  timestamp: 1622634196
layout:
  /header/: {  }
  /navigation/:
    -
      - menu-8272
  /showcase/:
    -
      - position-position-4747
  /feature/: {  }
  /main/:
    -
      - system-messages-4475
    -
      - position-position-6141
    -
      - system-content-9502
    -
      - position-position-5433
  /subfeature/: {  }
  /footer/:
    -
      - position-footer
  offcanvas:
    -
      - mobile-menu-2054
structure:
  header:
    attributes:
      boxed: ''
  navigation:
    type: section
    attributes:
      boxed: ''
  showcase:
    type: section
    attributes:
      boxed: ''
  feature:
    type: section
    attributes:
      boxed: ''
  main:
    attributes:
      boxed: ''
  subfeature:
    type: section
    attributes:
      class: flush
      boxed: ''
  footer:
    attributes:
      boxed: ''
content:
  position-position-4747:
    title: 'Module Position'
    attributes:
      key: showcase
  position-position-6141:
    title: 'Module Position'
    attributes:
      key: content-top
  position-position-5433:
    title: 'Module Position'
    attributes:
      key: content-bottom
  position-footer:
    attributes:
      key: footer
  mobile-menu-2054:
    title: 'Mobile Menu'
