version: 2
preset:
  image: 'gantry-admin://images/layouts/home.png'
  name: home
  timestamp: 1622634196
layout:
  /header/: {  }
  /navigation/:
    -
      - menu-8272
  /showcase/: {  }
  /feature/: {  }
  /main/:
    -
      - system-messages-4475
    -
      - system-content-9502
  /subfeature/:
    -
      - sample-3
  /footer/:
    -
      - position-footer
    -
      - 'copyright-5918 33.3'
      - 'social-3270 33.3'
      - 'branding-1212 33.3'
  offcanvas:
    -
      - mobile-menu-2054
structure:
  header:
    attributes:
      boxed: ''
  navigation:
    type: section
    attributes:
      boxed: ''
  showcase:
    type: section
    attributes:
      boxed: ''
  feature:
    type: section
    attributes:
      boxed: ''
  main:
    attributes:
      boxed: ''
  subfeature:
    type: section
    attributes:
      class: flush
      boxed: ''
  footer:
    attributes:
      boxed: ''
content:
  sample-3:
    title: 'Key Features'
    attributes:
      headline: 'Key Features'
      description: '<p>Gantry 5 is packed full of features created to empower the development of designs into fully functional layouts with the absolute minimum effort and fuss</p>'
      samples:
        -
          icon: 'fa fa-code'
          subtitle: ''
          description: '<p>Gantry 5 leverages the power of <a href="http://twig.sensiolabs.org/">Twig</a> to make creating powerful, dynamic themes quick and easy.</p>'
          title: 'Twig Templating'
        -
          icon: 'fa fa-newspaper-o'
          subtitle: ''
          description: '<p>Drag-and-drop functionality gives you the power to place content blocks, resize them, and configure their unique settings in seconds.</p>'
          title: 'Layout Manager'
        -
          icon: 'fa fa-cubes'
          subtitle: ''
          description: '<p>Create, configure, and manage content blocks as well as special features and functionality with the powerful particle system.</p>'
          title: 'Particles System'
  position-footer:
    attributes:
      key: footer
  social-3270:
    attributes:
      css:
        class: social-items
      items:
        -
          icon: 'fa fa-twitter'
          text: Twitter
          link: 'http://twitter.com/rockettheme'
          name: Twitter
        -
          icon: 'fa fa-facebook'
          text: Facebook
          link: 'http://facebook.com/rockettheme'
          name: Facebook
        -
          icon: 'fa fa-google'
          text: Google
          link: 'http://plus.google.com/+rockettheme'
          name: Google
        -
          icon: 'fa fa-rss'
          text: RSS
          link: 'http://www.rockettheme.com/product-updates?rss'
          name: RSS
    block:
      variations: center
  branding-1212:
    block:
      variations: align-right
  mobile-menu-2054:
    title: 'Mobile Menu'
