name: _body_only
timestamp: 1622634197
version: 7
preset:
  image: 'gantry-admin://images/layouts/body-only.png'
  name: _body_only
  timestamp: 1622634196
positions: {  }
sections:
  main: Main
particles:
  messages:
    system-messages-4662: 'System Messages'
  content:
    system-content-4596: 'Page Content'
inherit: {  }
